import { lazyQuadProgram } from './lazyQuadProgram';
import acidsquelchFrag from './assets/acidsquelch.frag?shader';
import acidsquiggleFrag from './assets/acidsquiggle.frag?shader';
import auroraribbonFrag from './assets/auroraribbon.frag?shader';
import binaryrainFrag from './assets/binaryrain.frag?shader';
import blackoutflashFrag from './assets/blackoutflash.frag?shader';
import blocknoiseFrag from './assets/blocknoise.frag?shader';
import bokehparticlesFrag from './assets/bokehparticles.frag?shader';
import boxFrag from './assets/box.frag?shader';
import boxarrayFrag from './assets/boxarray.frag?shader';
import bpminterferenceFrag from './assets/bpminterference.frag?shader';
import cagetunnelFrag from './assets/cagetunnel.frag?shader';
import cassettereelFrag from './assets/cassettereel.frag?shader';
import causticsFrag from './assets/caustics.frag?shader';
import cellularautomatonFrag from './assets/cellularautomaton.frag?shader';
import checkerskyFrag from './assets/checkersky.frag?shader';
import chromaticzoomFrag from './assets/chromaticzoom.frag?shader';
import chromechainFrag from './assets/chromechain.frag?shader';
import chromelogoFrag from './assets/chromelogo.frag?shader';
import circletunnelFrag from './assets/circletunnel.frag?shader';
import crtphosphorFrag from './assets/crtphosphor.frag?shader';
import cubetunnelFrag from './assets/cubetunnel.frag?shader';
import cymaticsFrag from './assets/cymatics.frag?shader';
import datamoshFrag from './assets/datamosh.frag?shader';
import dichroicglassFrag from './assets/dichroicglass.frag?shader';
import domainwarpFrag from './assets/domainwarp.frag?shader';
import dotmatrixFrag from './assets/dotmatrix.frag?shader';
import fbmFrag from './assets/fbm.frag?shader';
import flashgridFrag from './assets/flashgrid.frag?shader';
import fleshtunnelFrag from './assets/fleshtunnel.frag?shader';
import floweroflifeFrag from './assets/floweroflife.frag?shader';
import frostcrystalFrag from './assets/frostcrystal.frag?shader';
import geodesicdomeFrag from './assets/geodesicdome.frag?shader';
import glitchtextFrag from './assets/glitchtext.frag?shader';
import godrayFrag from './assets/godray.frag?shader';
import heartbeatscaleFrag from './assets/heartbeatscale.frag?shader';
import hextunnelFrag from './assets/hextunnel.frag?shader';
import hologramlogoFrag from './assets/hologramlogo.frag?shader';
import honeycombpulseFrag from './assets/honeycombpulse.frag?shader';
import impossiblestairsFrag from './assets/impossiblestairs.frag?shader';
import interlaceflickerFrag from './assets/interlaceflicker.frag?shader';
import isocubesFrag from './assets/isocubes.frag?shader';
import jumpcubetunnelFrag from './assets/jumpcubetunnel.frag?shader';
import kaleidofoldFrag from './assets/kaleidofold.frag?shader';
import kaleidojuliaFrag from './assets/kaleidojulia.frag?shader';
import kaleidotextFrag from './assets/kaleidotext.frag?shader';
import kickshakeFrag from './assets/kickshake.frag?shader';
import latticeFrag from './assets/lattice.frag?shader';
import lavametalstreamFrag from './assets/lavametalstream.frag?shader';
import lensflareFrag from './assets/lensflare.frag?shader';
import liquidmercuryFrag from './assets/liquidmercury.frag?shader';
import lissajousFrag from './assets/lissajous.frag?shader';
import lsystemtreeFrag from './assets/lsystemtree.frag?shader';
import mandelbrotzoomFrag from './assets/mandelbrotzoom.frag?shader';
import marbleveinsFrag from './assets/marbleveins.frag?shader';
import metalwavepoolFrag from './assets/metalwavepool.frag?shader';
import metatronscubeFrag from './assets/metatronscube.frag?shader';
import mirrorballFrag from './assets/mirrorball.frag?shader';
import mirrorcorridorFrag from './assets/mirrorcorridor.frag?shader';
import mirrorcubetowerFrag from './assets/mirrorcubetower.frag?shader';
import moireFrag from './assets/moire.frag?shader';
import mudcrackFrag from './assets/mudcrack.frag?shader';
import musicFrag from './assets/music.frag?shader';
import noiseauraFrag from './assets/noiseaura.frag?shader';
import nopFrag from './assets/nop.frag?shader';
import particlepolyhedronFrag from './assets/particlepolyhedron.frag?shader';
import patchcableFrag from './assets/patchcable.frag?shader';
import penroseFrag from './assets/penrose.frag?shader';
import perlinwormFrag from './assets/perlinworm.frag?shader';
import pinartFrag from './assets/pinart.frag?shader';
import pipeorganFrag from './assets/pipeorgan.frag?shader';
import pistongridFrag from './assets/pistongrid.frag?shader';
import plasmacloudFrag from './assets/plasmacloud.frag?shader';
import platonicmorphFrag from './assets/platonicmorph.frag?shader';
import postFrag from './assets/post.frag?shader';
import prismspectrumFrag from './assets/prismspectrum.frag?shader';
import pulsebarsFrag from './assets/pulsebars.frag?shader';
import pulsefloorFrag from './assets/pulsefloor.frag?shader';
import qrglitchFrag from './assets/qrglitch.frag?shader';
import radialburst8Frag from './assets/radialburst8.frag?shader';
import radialspectrumFrag from './assets/radialspectrum.frag?shader';
import reactiondiffusionFrag from './assets/reactiondiffusion.frag?shader';
import refractioncaveFrag from './assets/refractioncave.frag?shader';
import rgbsplitFrag from './assets/rgbsplit.frag?shader';
import ridgedmountainsFrag from './assets/ridgedmountains.frag?shader';
import sampleholdFrag from './assets/samplehold.frag?shader';
import scanwipeFrag from './assets/scanwipe.frag?shader';
import skeletalcubeglowFrag from './assets/skeletalcubeglow.frag?shader';
import smileyFrag from './assets/smiley.frag?shader';
import spikedblobFrag from './assets/spikedblob.frag?shader';
import spiralkaleidoFrag from './assets/spiralkaleido.frag?shader';
import startunnelFrag from './assets/startunnel.frag?shader';
import steelballpitFrag from './assets/steelballpit.frag?shader';
import stellatedpolyFrag from './assets/stellatedpoly.frag?shader';
import stepsequencerFrag from './assets/stepsequencer.frag?shader';
import strobecheckerwalkFrag from './assets/strobecheckerwalk.frag?shader';
import strobesweepFrag from './assets/strobesweep.frag?shader';
import swirlFrag from './assets/swirl.frag?shader';
import symmetrysmearFrag from './assets/symmetrysmear.frag?shader';
import tesseractFrag from './assets/tesseract.frag?shader';
import textFrag from './assets/text.frag?shader';
import toruswireknotFrag from './assets/toruswireknot.frag?shader';
import trigridFrag from './assets/trigrid.frag?shader';
import tunerstaticFrag from './assets/tunerstatic.frag?shader';
import twistcorridorFrag from './assets/twistcorridor.frag?shader';
import vhsnoiseFrag from './assets/vhsnoise.frag?shader';
import voronoishellFrag from './assets/voronoishell.frag?shader';
import voronoishutterFrag from './assets/voronoishutter.frag?shader';
import wagonwheelFrag from './assets/wagonwheel.frag?shader';
import waveformpulseringFrag from './assets/waveformpulsering.frag?shader';
import waveformtubeFrag from './assets/waveformtube.frag?shader';
import websymmetryFrag from './assets/websymmetry.frag?shader';
import wireglobeFrag from './assets/wireglobe.frag?shader';
import wormholeFrag from './assets/wormhole.frag?shader';
import { programs } from './programs';

// -- programs -------------------------------------------------------------------------------------
// Compiles every shader in the intro.
// This is where the programs come from in the prod build as well, not just on a dev build HMR.

programs.acidsquelch = lazyQuadProgram(acidsquelchFrag);
programs.acidsquiggle = lazyQuadProgram(acidsquiggleFrag);
programs.auroraribbon = lazyQuadProgram(auroraribbonFrag);
programs.binaryrain = lazyQuadProgram(binaryrainFrag);
programs.blackoutflash = lazyQuadProgram(blackoutflashFrag);
programs.blocknoise = lazyQuadProgram(blocknoiseFrag);
programs.bokehparticles = lazyQuadProgram(bokehparticlesFrag);
programs.box = lazyQuadProgram(boxFrag);
programs.boxarray = lazyQuadProgram(boxarrayFrag);
programs.bpminterference = lazyQuadProgram(bpminterferenceFrag);
programs.cagetunnel = lazyQuadProgram(cagetunnelFrag);
programs.cassettereel = lazyQuadProgram(cassettereelFrag);
programs.caustics = lazyQuadProgram(causticsFrag);
programs.cellularautomaton = lazyQuadProgram(cellularautomatonFrag);
programs.checkersky = lazyQuadProgram(checkerskyFrag);
programs.chromaticzoom = lazyQuadProgram(chromaticzoomFrag);
programs.chromechain = lazyQuadProgram(chromechainFrag);
programs.chromelogo = lazyQuadProgram(chromelogoFrag);
programs.circletunnel = lazyQuadProgram(circletunnelFrag);
programs.crtphosphor = lazyQuadProgram(crtphosphorFrag);
programs.cubetunnel = lazyQuadProgram(cubetunnelFrag);
programs.cymatics = lazyQuadProgram(cymaticsFrag);
programs.datamosh = lazyQuadProgram(datamoshFrag);
programs.dichroicglass = lazyQuadProgram(dichroicglassFrag);
programs.domainwarp = lazyQuadProgram(domainwarpFrag);
programs.dotmatrix = lazyQuadProgram(dotmatrixFrag);
programs.fbm = lazyQuadProgram(fbmFrag);
programs.flashgrid = lazyQuadProgram(flashgridFrag);
programs.fleshtunnel = lazyQuadProgram(fleshtunnelFrag);
programs.floweroflife = lazyQuadProgram(floweroflifeFrag);
programs.frostcrystal = lazyQuadProgram(frostcrystalFrag);
programs.geodesicdome = lazyQuadProgram(geodesicdomeFrag);
programs.glitchtext = lazyQuadProgram(glitchtextFrag);
programs.godray = lazyQuadProgram(godrayFrag);
programs.heartbeatscale = lazyQuadProgram(heartbeatscaleFrag);
programs.hextunnel = lazyQuadProgram(hextunnelFrag);
programs.hologramlogo = lazyQuadProgram(hologramlogoFrag);
programs.honeycombpulse = lazyQuadProgram(honeycombpulseFrag);
programs.impossiblestairs = lazyQuadProgram(impossiblestairsFrag);
programs.interlaceflicker = lazyQuadProgram(interlaceflickerFrag);
programs.isocubes = lazyQuadProgram(isocubesFrag);
programs.jumpcubetunnel = lazyQuadProgram(jumpcubetunnelFrag);
programs.kaleidofold = lazyQuadProgram(kaleidofoldFrag);
programs.kaleidojulia = lazyQuadProgram(kaleidojuliaFrag);
programs.kaleidotext = lazyQuadProgram(kaleidotextFrag);
programs.kickshake = lazyQuadProgram(kickshakeFrag);
programs.lattice = lazyQuadProgram(latticeFrag);
programs.lavametalstream = lazyQuadProgram(lavametalstreamFrag);
programs.lensflare = lazyQuadProgram(lensflareFrag);
programs.liquidmercury = lazyQuadProgram(liquidmercuryFrag);
programs.lissajous = lazyQuadProgram(lissajousFrag);
programs.lsystemtree = lazyQuadProgram(lsystemtreeFrag);
programs.mandelbrotzoom = lazyQuadProgram(mandelbrotzoomFrag);
programs.marbleveins = lazyQuadProgram(marbleveinsFrag);
programs.metalwavepool = lazyQuadProgram(metalwavepoolFrag);
programs.metatronscube = lazyQuadProgram(metatronscubeFrag);
programs.mirrorball = lazyQuadProgram(mirrorballFrag);
programs.mirrorcorridor = lazyQuadProgram(mirrorcorridorFrag);
programs.mirrorcubetower = lazyQuadProgram(mirrorcubetowerFrag);
programs.moire = lazyQuadProgram(moireFrag);
programs.mudcrack = lazyQuadProgram(mudcrackFrag);
programs.music = lazyQuadProgram(musicFrag);
programs.noiseaura = lazyQuadProgram(noiseauraFrag);
programs.nop = lazyQuadProgram(nopFrag);
programs.particlepolyhedron = lazyQuadProgram(particlepolyhedronFrag);
programs.patchcable = lazyQuadProgram(patchcableFrag);
programs.penrose = lazyQuadProgram(penroseFrag);
programs.perlinworm = lazyQuadProgram(perlinwormFrag);
programs.pinart = lazyQuadProgram(pinartFrag);
programs.pipeorgan = lazyQuadProgram(pipeorganFrag);
programs.pistongrid = lazyQuadProgram(pistongridFrag);
programs.plasmacloud = lazyQuadProgram(plasmacloudFrag);
programs.platonicmorph = lazyQuadProgram(platonicmorphFrag);
programs.post = lazyQuadProgram(postFrag);
programs.prismspectrum = lazyQuadProgram(prismspectrumFrag);
programs.pulsebars = lazyQuadProgram(pulsebarsFrag);
programs.pulsefloor = lazyQuadProgram(pulsefloorFrag);
programs.qrglitch = lazyQuadProgram(qrglitchFrag);
programs.radialburst8 = lazyQuadProgram(radialburst8Frag);
programs.radialspectrum = lazyQuadProgram(radialspectrumFrag);
programs.reactiondiffusion = lazyQuadProgram(reactiondiffusionFrag);
programs.refractioncave = lazyQuadProgram(refractioncaveFrag);
programs.rgbsplit = lazyQuadProgram(rgbsplitFrag);
programs.ridgedmountains = lazyQuadProgram(ridgedmountainsFrag);
programs.samplehold = lazyQuadProgram(sampleholdFrag);
programs.scanwipe = lazyQuadProgram(scanwipeFrag);
programs.skeletalcubeglow = lazyQuadProgram(skeletalcubeglowFrag);
programs.smiley = lazyQuadProgram(smileyFrag);
programs.spikedblob = lazyQuadProgram(spikedblobFrag);
programs.spiralkaleido = lazyQuadProgram(spiralkaleidoFrag);
programs.startunnel = lazyQuadProgram(startunnelFrag);
programs.steelballpit = lazyQuadProgram(steelballpitFrag);
programs.stellatedpoly = lazyQuadProgram(stellatedpolyFrag);
programs.stepsequencer = lazyQuadProgram(stepsequencerFrag);
programs.strobecheckerwalk = lazyQuadProgram(strobecheckerwalkFrag);
programs.strobesweep = lazyQuadProgram(strobesweepFrag);
programs.swirl = lazyQuadProgram(swirlFrag);
programs.symmetrysmear = lazyQuadProgram(symmetrysmearFrag);
programs.tesseract = lazyQuadProgram(tesseractFrag);
programs.text = lazyQuadProgram(textFrag);
programs.toruswireknot = lazyQuadProgram(toruswireknotFrag);
programs.trigrid = lazyQuadProgram(trigridFrag);
programs.tunerstatic = lazyQuadProgram(tunerstaticFrag);
programs.twistcorridor = lazyQuadProgram(twistcorridorFrag);
programs.vhsnoise = lazyQuadProgram(vhsnoiseFrag);
programs.voronoishell = lazyQuadProgram(voronoishellFrag);
programs.voronoishutter = lazyQuadProgram(voronoishutterFrag);
programs.wagonwheel = lazyQuadProgram(wagonwheelFrag);
programs.waveformpulsering = lazyQuadProgram(waveformpulseringFrag);
programs.waveformtube = lazyQuadProgram(waveformtubeFrag);
programs.websymmetry = lazyQuadProgram(websymmetryFrag);
programs.wireglobe = lazyQuadProgram(wireglobeFrag);
programs.wormhole = lazyQuadProgram(wormholeFrag);

// -- hot ------------------------------------------------------------------------------------------
if (import.meta.hot) {
  import.meta.hot.accept();
}
